FPS = 60

PLAYERS = ["fly", "frog", "spider"]

WIDTH = 1000
HEIGHT = 800
RATIO = 3
FIELD_WIDTH = 160 * RATIO
FIELD_HEIGHT = 157 * RATIO
PLANKS_X = (WIDTH - FIELD_WIDTH) / 2
PLANKS_Y = (HEIGHT - FIELD_HEIGHT) / 2

PLANK_WIDTH = 156 * RATIO
PLANK_HEIGHT = 29 * RATIO

CELLS_X = 2 * RATIO
CELLS_Y = 3 * RATIO
CELLS_GAP_X = 2 * RATIO
CELLS_GAP_Y = 2 * RATIO
CELL_SIZE = 27 * RATIO

CELLS = 5

BUSH_STOP_X = 1250