FPS = 60

PLAYERS = ["fly", "frog", "spider"]

WIDTH = 1000
HEIGHT = 800
RATIO = 3

LOBBY_BUTTON_GAP = 20
LOBBY_BUTTON_WIDTH = 444 / 100 * 15
LOBBY_BUTTON_HEIGHT = 470 / 100 * 15
BUTTON_SCALE = (0.15, 0.15)

FLY_BUTTON_X = WIDTH / 2
FLY_BUTTON_Y = HEIGHT / 2
BUG_BUTTON_X = WIDTH / 2 - LOBBY_BUTTON_WIDTH - LOBBY_BUTTON_GAP
BUG_BUTTON_Y = HEIGHT / 2
FROG_BUTTON_X = WIDTH / 2 + LOBBY_BUTTON_WIDTH + LOBBY_BUTTON_GAP
FROG_BUTTON_Y = HEIGHT / 2

FIELD_WIDTH = 160 * RATIO
FIELD_HEIGHT = 157 * RATIO
PLANKS_X = (WIDTH - FIELD_WIDTH) / 2
PLANKS_Y = (HEIGHT - FIELD_HEIGHT) / 2

PLANK_WIDTH = 156 * RATIO
PLANK_HEIGHT = 29 * RATIO

CELLS_X = 2 * RATIO
CELLS_Y = 3 * RATIO
CELLS_GAP_X = 2 * RATIO
CELLS_GAP_Y = 2 * RATIO
CELL_SIZE = 27 * RATIO

CELLS = 5

BUSH_STOP_OUT_X = 1250
BUSH_STOP_IN_X = 1080

L_BUSH_START_X = -80
R_BUSH_START_X = 1080

TABLE_IN_SPEED = 30
TABLE_OUT_SPEED = -5
TABLE_IN_SPEED_CENTER = 42
TABLE_INITIAL = (500, -200)

TABLE_HEIGHT = 340 / 2